language: python
sudo: required
services:
  - docker
script:
  - make docker/build
before_install:
  - pip install codecov
after_success:
  - codecov
deploy:
  provider: pypi
  user: kpn-digital
  password:
    secure: gN2OOf0+oArNdTEgbk500oA7jEECpzmwWpNMKFGYBJ5Tf77mGAECWADhjSj3YZt278HG8UpLc32Cn8KnbcJO9bCmOdlzFAjjHbIsTP8wWsPVQLKE2kSFC2RJThokwWRmkSF+Qk8OAVgF8PQdNaWJP27MgPTgCpf0oVesvD8vuTrjgy4hPfmQDGMbXZsn82ouwUia9XrwVcH2SxSN4AZ0ETG11XZVuuaOkL+OxIcSbLds8JmGXjejMuFEXVaFtJOwiDYMyZurFQQIgPOWI3dGZUuj2d8+fN+S3WnPrsgzikDKutWpx5xuqmTSGpOMgaMBoFhFVI+Iz84yf516l2LxWkyErztKhrsSsZtgGL7U/FZVVVmzPXDsVAJSNuvpb7wyJl/UCfy1SDoOAcR0Cn7G4PpOKhmJOiX7h9tVnKEQdqpGwS2XvWUXISyr7TS0NI+fFsrkb4TRCArxfHlVEzE+qKEiAViZkVvZthkty18WDbtYg67pV2wDJ7UO56GB9HDQXF//zBDUFmOibhvCC2wkOONFO+i3eYX/Z62xuVSrVheb+kwFrKcF/FntIrRdFBQMxtbMVZR4x7xhnPYcFw8RUIab2CY+MdzLiDX2AD5qNYGtmUu00iV2ku5tbHgp4jJNcXlFvHHN6/syKCzAT3GiDFsXAA2Zgr6fYEnh4RoIPOw=
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
